package jblis.constants;

public interface blisHiddenConstants {
    int BLIS_CONJ_NUM_BITS = 1;
    int BLIS_DATATYPE_SHIFT = 0;
    int BLIS_DOMAIN_NUM_BITS = 1;
    int BLIS_TRANS_NUM_BITS = 1;
    int BLIS_PRECISION_NUM_BITS = 2;
    int BLIS_DATATYPE_NUM_BITS = BLIS_DOMAIN_NUM_BITS + BLIS_PRECISION_NUM_BITS;
    int BLIS_CONJTRANS_SHIFT = BLIS_DATATYPE_SHIFT + BLIS_DATATYPE_NUM_BITS;
    int BLIS_TRANS_SHIFT = BLIS_CONJTRANS_SHIFT;
    int BLIS_CONJ_SHIFT = (   BLIS_TRANS_SHIFT + BLIS_TRANS_NUM_BITS );
    int BLIS_CONJ_BIT = ( ( ( 1 << BLIS_CONJ_NUM_BITS              ) - 1 ) << BLIS_CONJ_SHIFT );
    int BLIS_BITVAL_CONJ = BLIS_CONJ_BIT;

    int BLIS_TRANS_BIT = ( ( ( 1 << BLIS_TRANS_NUM_BITS             ) - 1 ) << BLIS_TRANS_SHIFT );
    int BLIS_BITVAL_TRANS = BLIS_TRANS_BIT;
    int BLIS_BITVAL_CONJ_TRANS = ( BLIS_CONJ_BIT | BLIS_TRANS_BIT );

    int BLIS_UPPER_NUM_BITS = 1;
    int BLIS_DIAG_NUM_BITS = 1;
    int BLIS_LOWER_NUM_BITS = 1;
    int BLIS_CONJTRANS_NUM_BITS = ( BLIS_TRANS_NUM_BITS + BLIS_CONJ_NUM_BITS );
    int BLIS_UPLO_SHIFT = ( BLIS_CONJTRANS_SHIFT + BLIS_CONJTRANS_NUM_BITS );
    int BLIS_UPPER_SHIFT = (   BLIS_UPLO_SHIFT );
    int BLIS_DIAG_SHIFT  = (   BLIS_UPPER_SHIFT + BLIS_UPPER_NUM_BITS );
    int BLIS_LOWER_SHIFT  = (   BLIS_DIAG_SHIFT + BLIS_DIAG_NUM_BITS );
    int BLIS_UPPER_BIT  = ( ( ( 1 << BLIS_UPPER_NUM_BITS             ) - 1 ) << BLIS_UPPER_SHIFT );
    int BLIS_DIAG_BIT =  ( ( ( 1 << BLIS_DIAG_NUM_BITS              ) - 1 ) << BLIS_DIAG_SHIFT );
    int BLIS_LOWER_BIT = ( ( ( 1 << BLIS_LOWER_NUM_BITS             ) - 1 ) << BLIS_LOWER_SHIFT );
    int BLIS_UPLO_NUM_BITS = ( BLIS_UPPER_NUM_BITS + BLIS_DIAG_NUM_BITS + BLIS_LOWER_NUM_BITS );
    int BLIS_UPLO_BITS = ( ( ( 1 << BLIS_UPLO_NUM_BITS              ) - 1 ) << BLIS_UPLO_SHIFT );

    int BLIS_BITVAL_ZEROS = 0x0;
    int BLIS_BITVAL_UPPER = ( BLIS_UPPER_BIT | BLIS_DIAG_BIT );
    int BLIS_BITVAL_LOWER = ( BLIS_LOWER_BIT | BLIS_DIAG_BIT );
    int BLIS_BITVAL_DENSE = BLIS_UPLO_BITS;

    int BLIS_UNIT_DIAG_SHIFT = ( BLIS_UPLO_SHIFT + BLIS_UPLO_NUM_BITS );
    int BLIS_UNIT_DIAG_NUM_BITS = 1;
    int BLIS_UNIT_DIAG_BIT = ( ( ( 1 << BLIS_UNIT_DIAG_NUM_BITS         ) - 1 ) << BLIS_UNIT_DIAG_SHIFT );
    int BLIS_BITVAL_UNIT_DIAG = BLIS_UNIT_DIAG_BIT;

    int BLIS_NUM_LOOPS = 6;

    int BLIS_DOMAIN_SHIFT =    (   BLIS_DATATYPE_SHIFT );
    int BLIS_PRECISION_SHIFT = (   BLIS_DOMAIN_SHIFT + BLIS_DOMAIN_NUM_BITS );
    int BLIS_DOMAIN_BIT  =  ( ( ( 1 << BLIS_DOMAIN_NUM_BITS            ) - 1 ) << BLIS_DOMAIN_SHIFT );
    int BLIS_BITVAL_DOUBLE_PREC = ( 0x1 << BLIS_PRECISION_SHIFT );


    int BLIS_DATATYPE_BITS = ( ( ( 1 << BLIS_DATATYPE_NUM_BITS          ) - 1 ) << BLIS_DATATYPE_SHIFT );
    int BLIS_BITVAL_SINGLE_PREC = 0x0;

    int BLIS_PACK_PANEL_NUM_BITS  = 1;
    int BLIS_PACK_FORMAT_NUM_BITS          = 4;
    int BLIS_PACK_NUM_BITS                 = 1;
    int BLIS_PACK_SCHEMA_NUM_BITS = ( BLIS_PACK_PANEL_NUM_BITS + BLIS_PACK_FORMAT_NUM_BITS + BLIS_PACK_NUM_BITS );
    int BLIS_INVERT_DIAG_NUM_BITS = 1;
    int BLIS_PACK_REV_IF_UPPER_NUM_BITS    = 1;
    int BLIS_PACK_REV_IF_LOWER_NUM_BITS    = 1;
    int BLIS_PACK_BUFFER_NUM_BITS          = 2;
    int BLIS_INVERT_DIAG_SHIFT = ( BLIS_UNIT_DIAG_SHIFT + BLIS_UNIT_DIAG_NUM_BITS );
    int BLIS_PACK_SCHEMA_SHIFT = ( BLIS_INVERT_DIAG_SHIFT + BLIS_INVERT_DIAG_NUM_BITS );
    int BLIS_PACK_REV_IF_UPPER_SHIFT = ( BLIS_PACK_SCHEMA_SHIFT + BLIS_PACK_SCHEMA_NUM_BITS );
    int BLIS_PACK_REV_IF_LOWER_SHIFT = ( BLIS_PACK_REV_IF_UPPER_SHIFT + BLIS_PACK_REV_IF_UPPER_NUM_BITS );
    int BLIS_PACK_BUFFER_SHIFT = ( BLIS_PACK_REV_IF_LOWER_SHIFT + BLIS_PACK_REV_IF_LOWER_NUM_BITS );
    int BLIS_STRUC_SHIFT =  ( BLIS_PACK_BUFFER_SHIFT + BLIS_PACK_BUFFER_NUM_BITS );
    int BLIS_BITVAL_GENERAL  =     0x0;
    int BLIS_BITVAL_HERMITIAN =    ( 0x1 << BLIS_STRUC_SHIFT );
    int BLIS_BITVAL_SYMMETRIC  =   ( 0x2 << BLIS_STRUC_SHIFT );
    int BLIS_BITVAL_TRIANGULAR  =  ( 0x3 << BLIS_STRUC_SHIFT );
}
