package jblis.constants;

public interface blisEnums extends blisHiddenConstants{
    int iBLIS_NO_CONJUGATE = (int)0L;
    int iBLIS_CONJUGATE = BLIS_BITVAL_CONJ;

    int iBLIS_NO_TRANSPOSE = 0;
    int iBLIS_TRANSPOSE         = BLIS_BITVAL_TRANS;
    int iBLIS_CONJ_NO_TRANSPOSE = BLIS_BITVAL_CONJ;
    int iBLIS_CONJ_TRANSPOSE    = BLIS_BITVAL_CONJ_TRANS;

    int iBLIS_LEFT = 0;
    int iBLIS_RIGHT = 1;

    int iBLIS_ZEROS = BLIS_BITVAL_ZEROS;
    int iBLIS_LOWER  = BLIS_BITVAL_LOWER;
    int iBLIS_UPPER  = BLIS_BITVAL_UPPER;
    int iBLIS_DENSE  = BLIS_BITVAL_DENSE;

    int iBLIS_NONUNIT_DIAG = 0;
    int iBLIS_UNIT_DIAG = BLIS_BITVAL_UNIT_DIAG;

    int BLIS_BITVAL_FLOAT_TYPE = 0;
    int BLIS_BITVAL_DOUBLE_TYPE = ( 0x1 << BLIS_PRECISION_SHIFT );
    int BLIS_BITVAL_SCOMPLEX_TYPE =  BLIS_DOMAIN_BIT;
    int BLIS_BITVAL_DCOMPLEX_TYPE =  ( BLIS_DOMAIN_BIT | BLIS_BITVAL_DOUBLE_PREC );
    int BLIS_BITVAL_INT_TYPE = 0x04;
    int BLIS_BITVAL_CONST_TYPE = 0x05;

    int BLIS_BITVAL_REAL =   0x0;
    int BLIS_BITVAL_COMPLEX = BLIS_DOMAIN_BIT;
}
